name: Run tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7, 3.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec
