name: Run tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec
